# Generated by Django 5.1.7 on 2025-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('user_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='Avicast123', max_length=255)),
            ],
        ),
    ]
