# Generated by Django 5.1.7 on 2025-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardadminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadminuser',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
